In [1]:
import cv2

In [2]:
import numpy as np
import matplotlib as plt

In [5]:
img= cv2.imread('pexels-pixabay-60597 (1).jpg', cv2.IMREAD_COLOR)

In [9]:
cv2.imshow("image", img)

In [10]:
print(img)

[[[37 51 23]
  [37 51 23]
  [37 51 23]
  ...
  [37 51 23]
  [37 51 23]
  [37 51 23]]

 [[37 51 23]
  [37 51 23]
  [37 51 23]
  ...
  [37 51 23]
  [37 51 23]
  [37 51 23]]

 [[37 51 23]
  [37 51 23]
  [37 51 23]
  ...
  [37 51 23]
  [37 51 23]
  [37 51 23]]

 ...

 [[37 51 23]
  [37 51 23]
  [37 51 23]
  ...
  [37 51 23]
  [37 51 23]
  [37 51 23]]

 [[37 51 23]
  [37 51 23]
  [37 51 23]
  ...
  [37 51 23]
  [37 51 23]
  [37 51 23]]

 [[37 51 23]
  [37 51 23]
  [37 51 23]
  ...
  [37 51 23]
  [37 51 23]
  [37 51 23]]]
